 language: scala
 scala:
   - "2.10.3"
 jdk:
   - oraclejdk7
   - openjdk7
   - openjdk6
 before_script:
   - sh src/test/resources/setup_travis.sh
 env:
   - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
